#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

python manage.py register_analysis_functions

# make sure that the ORCID social app for django-all-auth is configured
#
# The template file 'orcid.yaml.template' was created by
#  python manage.py dumpdata --settings=config.settings.local -o orcid.yaml socialaccount.socialapp
# plus replaced the values of "client_id" and "secret" with environment variables.
#

python manage.py collectstatic --noinput

# create yaml file with actual values of environment variables
envsubst < orcid.yaml.template > orcid.yaml

python manage.py loaddata -v 2 orcid.yaml

# python manage.py dumpdata -a -o dumpdata.yaml

python manage.py runserver_plus 0.0.0.0:8000
