# Generated by Django 2.2.13 on 2020-08-26 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0019_remove_surface_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=10, null=True, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('license', models.CharField(choices=[('cc0-1.0', 'CC0 (Public Domain Dedication)'), ('ccby-4.0', 'CC BY 4.0'), ('ccbysa-4.0', 'CC BY-SA 4.0')], default='', max_length=12)),
                ('original_surface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_publications', to='manager.Surface')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('surface', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='manager.Surface')),
            ],
        ),
    ]
