# Generated by Django 2.2.13 on 2020-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
