# Generated by Django 2.2.13 on 2020-07-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_remove_surface_parent'),
        ('publication', '0002_publication_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='original_surface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_set', to='manager.Surface'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='surface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='manager.Surface'),
        ),
    ]
