# Generated by Django 2.2.13 on 2020-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publisher_orcid_id',
            field=models.CharField(default='', max_length=19),
        ),
    ]
