# Generated by Django 2.2.13 on 2020-07-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20200722_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='original_surface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_publications', to='manager.Surface'),
        ),
    ]
