# Generated by Django 2.2.20 on 2021-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publication_publisher_orcid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='license',
            field=models.CharField(choices=[('cc0-1.0', 'CC0 1.0 (Public Domain Dedication)'), ('ccby-4.0', 'CC BY 4.0'), ('ccbysa-4.0', 'CC BY-SA 4.0')], default='', max_length=12),
        ),
    ]
