# Generated by Django 2.2.13 on 2020-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20200722_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='short_url',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
