# Generated by Django 2.2.13 on 2020-08-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_publication_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='uuid',
        ),
    ]
