# Generated by Django 3.2.11 on 2022-02-03 14:41

from django.db import migrations


def transfer_author_names_to_author_instances(apps, schema_editor):
    """Convert author names to Author instances."""
    Publication = apps.get_model('publication', 'Publication')
    Researcher = apps.get_model('publication', 'Researcher')

    for pub in Publication.objects.all():
        authors_names = [a.strip() for a in pub.authors.split(',')]
        for author_name in authors_names:
            # find last name as last word
            *first_names, last_name = [name_part.strip() for name_part in author_name.split(" ")]

            # create author if he/she does not exist
            researcher, created = Researcher.objects.get_or_create(first_name=" ".join(first_names),
                                                                   last_name=last_name)
            pub.authors_list.add(researcher)


def transfer_author_instances_to_author_names(apps, schema_editor):
    """Convert author instances to Author names.

    This might cause data loss, because the author instances potentially
    include more data than just the name.
    """
    Publication = apps.get_model('publication', 'Publication')

    for pub in Publication.objects.all():
        pub.authors = ", ".join(f"{author.first_name} {author.last_name}" for author in pub.authors_list.all())
        pub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_create_researcher_model'),
    ]

    operations = [
        migrations.RunPython(transfer_author_names_to_author_instances,
                             reverse_code=transfer_author_instances_to_author_names),
    ]
