# Generated by Django 3.2.11 on 2022-02-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_transfer_authors_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
    ]
