# Generated by Django 3.2.11 on 2022-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_remove_publication_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi_name',
            field=models.CharField(max_length=50),
        ),
    ]
