# Generated by Django 3.2.11 on 2022-02-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_remove_publication_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='authors_list',
            new_name='authors',
        ),
    ]
