# Generated by Django 3.2.11 on 2022-02-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_publication_doi_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='datacite_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_state',
            field=models.CharField(choices=[('draft', 'only visible in Fabrica, DOI can be deleted'), ('registered', 'registered with the DOI Resolver, cannot be deleted'), ('findable', 'registered with the DOI Resolver and indexed in DataCite Search, cannot be deleted')], default='', max_length=10),
        ),
    ]
