dist: bionic
#services:
#  - xvfb
language: python
cache: pip
addons:
  firefox: latest
  apt:
    packages:
      - firefox-geckodriver
env:
  global:
    - USE_DOCKER=no
    - DJANGO_SETTINGS_MODULE=config.settings.test
    - FIREFOX_BINARY_PATH=/usr/lib/firefox/firefox
    - GECKODRIVER_PATH=/usr/bin/geckodriver
python:
  - 3.7
#before_install:
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  # - sudo apt-get install libfftw3-dev libopenblas-dev chromium-chromedriver
  - sudo apt-get install libfftw3-dev libopenblas-dev
  - pip install -q -r requirements/test.txt
  - python manage.py collectstatic
  # - pip install selenium
script:
  # - pytest -v --splinter-webdriver=chrome --splinter-headless=true --splinter-webdriver-executable=/opt/google/chrome/chrome
  # - pytest -v --splinter-headless=true
  - pytest -v --ignore=splinter_tests
notifications:
  email:
    - roettger@tf.uni-freiburg.de
    # - lars.pastewka@imtek.uni-freiburg.de
