# Generated by Django 2.1.7 on 2019-04-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwargs', models.BinaryField()),
                ('task_id', models.CharField(max_length=155, null=True, unique=True)),
                ('task_state', models.CharField(choices=[('pe', 'pending'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success')], max_length=7)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('result', models.BinaryField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable name.', max_length=80, unique=True)),
                ('pyfunc', models.CharField(help_text='Name of Python function in topobank.analysis.functions', max_length=256)),
                ('automatic', models.BooleanField(default=False, help_text='If set, this analysis is automatically triggered for new topographies.')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AnalysisFunction'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='topography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Topography'),
        ),
    ]
