# Generated by Django 2.1.7 on 2019-04-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='topography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Topography'),
        ),
    ]
