# Generated by Django 2.1.11 on 2019-09-09 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0002_auto_20190729_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('combined_task_state', models.CharField(choices=[('pe', 'pending'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success')], max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysiscollection',
            name='analyses',
            field=models.ManyToManyField(to='analysis.Analysis'),
        ),
        migrations.AddField(
            model_name='analysiscollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
