# Generated by Django 2.0.6 on 2018-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_topography'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfunction',
            name='automatic',
            field=models.BooleanField(default=False, help_text='If set, this analysis is automatically triggered for new topographies.'),
        ),
        migrations.AlterField(
            model_name='analysisfunction',
            name='name',
            field=models.CharField(help_text='A human-readable name.', max_length=80, unique=True),
        ),
    ]
