# Generated by Django 2.1.11 on 2019-10-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20190909_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('dependency', 'major', 'minor', 'micro')},
        ),
    ]
