# Generated by Django 2.0.6 on 2018-09-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20180928_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
