# Generated by Django 2.2.13 on 2020-12-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_topography_thumbnail'),
        ('analysis', '0004_auto_20191007_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='surface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Surface'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='topography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Topography'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('topography__isnull', True), ('surface__isnull', False)), models.Q(('topography__isnull', False), ('surface__isnull', True)), _connector='OR'), name='unique_subject'),
        ),
    ]
