# Generated by Django 2.2.13 on 2021-01-25 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('analysis', '0004_auto_20191007_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfunction',
            name='automatic',
        ),
        migrations.RemoveField(
            model_name='analysisfunction',
            name='pyfunc',
        ),
        migrations.AddField(
            model_name='analysis',
            name='subject_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='subject_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='analysisfunction',
            name='card_view_flavor',
            field=models.CharField(choices=[('simple', 'Simple display of the results as raw data structure'), ('plot', 'Display results in a plot with multiple datasets'), ('power spectrum', 'Display results in a plot suitable for power spectrum'), ('contact mechanics', 'Display suitable for contact mechanics including special widgets'), ('rms table', 'Display a table with RMS values.')], default='simple', max_length=50),
        ),
        migrations.CreateModel(
            name='AnalysisFunctionImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ref', models.CharField(help_text="name of Python function in 'topobank.analysis.functions' module", max_length=256)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='analysis.AnalysisFunction')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddConstraint(
            model_name='analysisfunctionimplementation',
            constraint=models.UniqueConstraint(fields=('function', 'subject_type'), name='distinct_implementation'),
        ),
    ]
