# Generated by Django 2.2.13 on 2021-01-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20201211_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisfunction',
            name='automatic',
        ),
        migrations.RemoveField(
            model_name='analysisfunction',
            name='pyfunc',
        ),
    ]
