# Generated by Django 2.2.13 on 2021-01-25 11:37

from django.db import migrations


def move_topographies_to_subjects(apps, schema_editor):
    Analysis = apps.get_model('analysis', 'Analysis')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Topography = apps.get_model('manager', 'Topography')
    topography_content_type = ContentType.objects.get_for_model(Topography)

    for a in Analysis.objects.all():
        a.subject_id = a.topography_id
        a.subject_type = topography_content_type
        a.save()


def move_subjects_to_topographies(apps, schema_editor):
    Analysis = apps.get_model('analysis', 'Analysis')
    Topography = apps.get_model('manager', 'Topography')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    topography_content_type = ContentType.objects.get_for_model(Topography)

    for a in Analysis.objects.all():
        if isinstance(a.subject_type, topography_content_type):
            a.topography_id = a.subject_id
            a.save()
        else:
            a.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20210125_1235'),
    ]

    operations = [
        migrations.RunPython(
            move_topographies_to_subjects,
            move_subjects_to_topographies
        ),
    ]
