# Generated by Django 2.0.6 on 2018-11-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20180928_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='args',
        ),
    ]
