# Generated by Django 2.2.13 on 2021-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_topographies_to_generic_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='topography',
        ),
    ]
