# Generated by Django 2.2.20 on 2021-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_remove_analysis_topography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfunction',
            name='card_view_flavor',
            field=models.CharField(choices=[('simple', 'Simple display of the results as raw data structure'), ('plot', 'Display results in a plot with multiple datasets'), ('power spectrum', 'Display results in a plot suitable for power spectrum'), ('contact mechanics', 'Display suitable for contact mechanics including special widgets'), ('roughness parameters', 'Display a table with roughness parameters.')], default='simple', max_length=50),
        ),
    ]
