# Generated by Django 3.2.16 on 2022-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_analysis_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='dois',
            field=models.JSONField(default=list),
        ),
    ]
