# Generated by Django 3.2.16 on 2022-12-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_analysis_dois'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
