# Generated by Django 3.2.16 on 2023-01-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_analysis_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='extra',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
