# Generated by Django 3.2.18 on 2023-03-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_version_extra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('dependency', 'major', 'minor', 'micro', 'extra')},
        ),
    ]
