# Generated by Django 3.2.18 on 2023-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_alter_analysis_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='task_error',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='task_state',
            field=models.CharField(choices=[('pe', 'pending'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success'), ('no', 'not run')], default='no', max_length=7),
        ),
        migrations.AlterField(
            model_name='analysiscollection',
            name='combined_task_state',
            field=models.CharField(choices=[('pe', 'pending'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success'), ('no', 'not run')], max_length=7),
        ),
    ]
