# Generated by Django 3.2.18 on 2023-10-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
        ('analysis', '0021_auto_20230916_0908'),
    ]

    state_operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='version',
            name='dependency',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskapp.configuration'),
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Dependency',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
