# Generated by Django 4.2.7 on 2024-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_auto_20231009_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='task_memory',
            field=models.IntegerField(null=True),
        ),
    ]
