# Generated by Django 4.2.7 on 2024-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_analysis_task_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='task_memory',
            field=models.BigIntegerField(null=True),
        ),
    ]
