# Generated by Django 4.2.7 on 2024-02-04 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_rename_tagmodel_tag'),
        ('analysis', '0024_alter_analysis_task_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissubject',
            name='collection',
        ),
        migrations.AddField(
            model_name='analysissubject',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.tag'),
        ),
    ]
