# Generated by Django 4.2.14 on 2024-08-13 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forward_func(apps, schema_editor):
    Analysis = apps.get_model('analysis', 'analysis')
    for analysis in Analysis.objects.all():
        if len(analysis.users) == 0:
            analysis.delete()
        else:
            analysis.user = analysis.users.first()
            analysis.save()

def reverse_func(apps, schema_editor):
    Analysis = apps.get_model('analysis', 'analysis')
    for analysis in Analysis.objects.all():
        analysis.users.add(analysis.user)
        analysis.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0025_remove_analysissubject_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
            migrations.RunPython(
            forward_func,
            reverse_func
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='users',
        ),
    ]
