# Generated by Django 4.2.14 on 2024-08-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_folder_read_only"),
        ("authorization", "0001_initial"),
        ("analysis", "0025_remove_analysissubject_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="files.folder",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="permissions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authorization.permissionset",
            ),
        ),    ]
