# Generated by Django 4.2.14 on 2024-08-13 20:31

from django.conf import settings
from django.db import migrations


def forward_func(apps, schema_editor):
    Analysis = apps.get_model("analysis", "analysis")
    for analysis in Analysis.objects.all():
        if analysis.users.count() == 0:
            analysis.delete()
        else:
            analysis.user = analysis.users.first()
            analysis.save()


def reverse_func(apps, schema_editor):
    Analysis = apps.get_model("analysis", "analysis")
    for analysis in Analysis.objects.all():
        analysis.users.add(analysis.user)
        analysis.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0026_add_analysis_users"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
