# Generated by Django 4.2.14 on 2024-08-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0026_remove_analysis_users_analysis_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisCollection",
        ),
    ]
