# Generated by Django 4.2.14 on 2024-08-13 20:31

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def forward_func(apps, schema_editor):
    Analysis = apps.get_model("analysis", "Analysis")
    PermissionSet = apps.get_model("authorization", "PermissionSet")
    UserPermission = apps.get_model("authorization", "UserPermission")
    # Delete all analyses without a user (this will leave dangling files in the S3)
    Analysis.objects.select_related("users").annotate(nb_users=Count("users")).filter(
        nb_users=0
    ).delete()
    # Create permission sets for the remaining users
    for analysis in Analysis.objects.all():
        permissions = PermissionSet.objects.create()
        analysis.permissions = permissions
        for user in analysis.users.all():
            UserPermission.objects.create(parent=permissions, user=user, allow="view")
        analysis.save(update_fields=["permissions"])


def reverse_func(apps, schema_editor):
    Analysis = apps.get_model("analysis", "analysis")
    for analysis in Analysis.objects.all():
        analysis.users.add(analysis.user)
        analysis.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0026_add_analysis_permissions_folder"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
