# Generated by Django 4.2.15 on 2024-09-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0029_delete_analysiscollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="launcher_task_id",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="task_id",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
