# Generated by Django 4.2.16 on 2024-10-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_analysis_task_traceback_alter_analysis_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysisfunction'),
        ),
    ]
