# Generated by Django 4.2.16 on 2025-01-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_analysis_dependencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisfunction',
            old_name='name',
            new_name='display_name',
        ),
    ]
