# Generated by Django 4.2.16 on 2025-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_rename_name_analysisfunction_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfunction',
            name='name',
            field=models.TextField(default='', help_text='The name of this analysis function.'),
        ),
        migrations.AlterField(
            model_name='analysisfunction',
            name='display_name',
            field=models.TextField(help_text='A human-readable name.'),
        ),
    ]
