# Generated by Django 4.2.18 on 2025-04-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_analysisfunction_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='description',
            field=models.TextField(help_text='Optional description of the analysis. Used to add context to prediction reports template', null=True),
        ),
    ]
