# Generated by Django 4.2.21 on 2025-05-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0038_rename_end_time_analysis_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='invalidation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
