# Generated by Django 5.2.4 on 2025-09-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_analysis_deprecation_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkflowTemplate',
        ),
    ]
