# Generated by Django 5.2.5 on 2025-08-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0039_analysis_deprecation_time"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnalysisFunction",
            new_name="Workflow",
        ),
    ]
