# Generated by Django 5.2.5 on 2025-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0040_rename_analysisfunction_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="display_name",
            field=models.TextField(help_text="Human-readable name"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.TextField(help_text="Internal unique identifier"),
        ),
    ]
