# Generated by Django 5.2.5 on 2025-08-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0041_alter_workflow_display_name_alter_workflow_name"),
        ("authorization", "0002_organizationpermission"),
        ("files", "0007_alter_manifest_unique_together"),
        ("taskapp", "0002_alter_configuration_table_alter_dependency_table_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Analysis",
            new_name="WorkflowResult",
        ),
    ]
