# Generated by Django 5.2.5 on 2025-08-29 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0042_rename_analysis_workflowresult"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflowresult",
            options={},
        ),
        migrations.AlterField(
            model_name="workflowresult",
            name="function",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="analysis.workflow",
            ),
        ),
    ]
