# Generated by Django 5.2.5 on 2025-08-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0043_alter_workflowresult_options_and_more"),
        ("manager", "0069_rename_creation_datetime_surface_creation_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnalysisSubject",
            new_name="WorkflowSubject",
        ),
    ]
