# Generated by Django 5.2.4 on 2025-09-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_delete_workflowtemplate'),
        ('analysis', '0044_rename_analysissubject_workflowsubject'),
    ]

    operations = [
    ]
