# Generated by Django 5.2.4 on 2025-09-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0044_rename_analysissubject_workflowsubject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkflowTemplate',
        ),
    ]
