# Generated by Django 5.2.7 on 2025-10-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0045_workflowresult_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
