# Generated by Django 5.2.7 on 2025-11-03 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0046_workflowresult_metadata'),
        ('organizations', '0002_alter_organization_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowresult',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workflowresult',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='workflowresult',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='workflowresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflowresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
