# Generated by Django 5.2.7 on 2025-11-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0047_rename_creation_time_workflowresult_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowresult',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the analysis.', null=True),
        ),
    ]
