# Generated by Django 5.2.10 on 2026-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0049_add_workflowresult_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='task_timer',
            field=models.JSONField(null=True),
        ),
    ]
