# Generated by Django 5.2.10 on 2026-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0050_add_task_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowresult',
            name='task_state',
            field=models.CharField(choices=[('pe', 'pending'), ('pd', 'pending dependencies'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success'), ('no', 'not run')], default='no', max_length=2),
        ),
    ]
