# Generated by Django 5.2.11 on 2026-03-15 14:01

from django.db import migrations, models

import topobank.analysis.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0053_workflowresult_result_func_subj_time_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowresult',
            name='subject_dispatch',
            field=models.OneToOneField(null=True, on_delete=topobank.analysis.models.cascade_or_set_null, to='analysis.workflowsubject'),
        ),
    ]
