# Generated by Django 5.2.13 on 2026-04-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0054_alter_workflowresult_subject_dispatch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowresult",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="workflowtemplate",
            name="permissions",
        ),
    ]
