# Generated by Django 5.2.11 on 2026-03-22 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0054_alter_workflowresult_subject_dispatch'),
        ('authorization', '0003_add_permission_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='node_key',
            field=models.CharField(blank=True, db_index=True, help_text="Node key within the plan DAG (e.g., 'workflow.function:subject:kwargshash')", max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='PlanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pe', 'pending'), ('ru', 'running'), ('su', 'success'), ('fa', 'failure')], default='pe', max_length=2)),
                ('plan_json', models.JSONField()),
                ('root_kwargs', models.JSONField(default=dict, help_text='Kwargs for the root workflow node')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.permissionset')),
                ('root_function', models.ForeignKey(help_text='The root workflow function of this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_as_root', to='analysis.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='workflowresult',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The execution plan this result is part of (if plan-based execution)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analysis.planrecord'),
        ),
        migrations.AddIndex(
            model_name='planrecord',
            index=models.Index(fields=['state', '-created_at'], name='plan_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='planrecord',
            index=models.Index(fields=['-created_at'], name='plan_created_idx'),
        ),
    ]
