# Generated by Django 5.2.13 on 2026-04-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0055_remove_workflowresult_permissions_and_more'),
        ('authorization', '0004_alter_userpermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.permissionset'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.permissionset'),
        ),
    ]
