# Generated by Django 5.2.11 on 2026-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0055_workflow_name_unique'),
        ('manager', '0078_surface_surface_active_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowresult',
            name='surfaces',
            field=models.ManyToManyField(blank=True, related_name='workflow_results', to='manager.surface'),
        ),
        migrations.AddField(
            model_name='workflowresult',
            name='surfaces_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
