# Generated by Django 5.2.13 on 2026-05-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0056_add_surfaces_m2m_and_subject_hash"),
        ("analysis", "0060_delete_workflowtemplate"),
    ]

    operations = []
