# Generated by Django 5.2.14 on 2026-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0062_collapse_workflowsubject"),
        ("manager", "0078_surface_surface_active_name_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowresult",
            name="surfaces",
            field=models.ManyToManyField(
                blank=True, related_name="workflow_result_sets", to="manager.surface"
            ),
        ),
    ]
