# Generated by Django 5.2.16 on 2026-07-25 09:52

import django.db.models.deletion
from django.db import migrations, models

import topobank.authorization.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0064_backfill_subject_hash"),
        # Only the initial migration of the authorization app is required (it
        # creates PermissionSet). The app is swappable, so depending on a later
        # migration would tie this to one particular authorization backend.
        ("authorization", "0001_initial"),
        # Likewise, only the migration that settles `Manifest` is needed. Naming
        # the latest files migration here would add a graph edge that reorders
        # the rename of Folder to ManifestSet ahead of the manager migrations
        # that still refer to the old name.
        ("files", "0007_alter_manifest_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultZipContainer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField(null=True, unique=True)),
                ("launcher_task_id", models.UUIDField(null=True, unique=True)),
                (
                    "task_state",
                    models.CharField(
                        choices=[
                            ("pe", "pending"),
                            ("pd", "pending dependencies"),
                            ("st", "started"),
                            ("re", "retry"),
                            ("fa", "failure"),
                            ("su", "success"),
                            ("no", "not run"),
                        ],
                        default="no",
                        max_length=2,
                    ),
                ),
                ("task_memory", models.BigIntegerField(null=True)),
                ("task_error", models.TextField(default="")),
                ("task_traceback", models.TextField(null=True)),
                ("task_submission_time", models.DateTimeField(null=True)),
                ("task_start_time", models.DateTimeField(null=True)),
                ("task_end_time", models.DateTimeField(null=True)),
                ("task_timer", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manifest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_zip_containers",
                        to="files.manifest",
                    ),
                ),
                (
                    "permissions",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authorization.permissionset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(topobank.authorization.mixins.PermissionMixin, models.Model),
        ),
    ]
