# Generated by Django 5.2.17 on 2026-09-11 06:24
"""
Join two migrations that were both numbered 0066 on different branches.

`0066_workflowresult_soft_delete` shipped on `main` in 1.72.0 and is applied on
production, so it cannot be renumbered. `0066_rename_subject_topography_measurement`
is the measurement-model branch's, unreleased. The two are independent -- one
adds soft-delete columns to `WorkflowResult`, the other renames its subject
foreign key -- so this merge carries no operations of its own.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0066_rename_subject_topography_measurement"),
        ("analysis", "0066_workflowresult_soft_delete"),
    ]

    operations = []
