# Generated by Django 4.2.21 on 2025-05-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow', models.CharField(choices=[('view', 'Read-only access'), ('edit', 'Change the model data'), ('full', 'Grant/revoke permissions of other users')], max_length=4)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_permissions', to='authorization.permissionset')),
            ],
            options={
                'unique_together': {('parent', 'organization')},
            },
        ),
    ]
