# Generated by Django 2.1.7 on 2019-03-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181105_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_skip_terms', 'Can skip all checkings for terms and conditions.'),)},
        ),
    ]
