# Generated by Django 4.2.16 on 2024-09-23 13:56

import django.db.models.deletion
from django.db import migrations, models

import topobank.authorization.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("manager", "0064_delete_property"),
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Property",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.TextField(default="prop")),
                        ("value_categorical", models.CharField(blank=True, null=True)),
                        ("value_numerical", models.FloatField(blank=True, null=True)),
                        ("unit", models.TextField(blank=True, null=True)),
                        (
                            "permissions",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authorization.permissionset",
                            ),
                        ),
                        (
                            "surface",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="properties",
                                to="manager.surface",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "manager_property",
                        "verbose_name_plural": "properties",
                        "unique_together": {("surface", "name")},
                    },
                    bases=(topobank.authorization.mixins.PermissionMixin, models.Model),
                ),
            ],
            # Don't create a new table
            database_operations=[],
        )
    ]
