# Generated by Django 4.2.16 on 2024-09-23 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="property",
            table=None,
        ),
    ]
