# Generated by Django 2.1.7 on 2019-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='category',
            field=models.TextField(choices=[('exp', 'experimental data'), ('sim', 'simulated data'), ('dum', 'dummy data')], null=True),
        ),
    ]
