# Generated by Django 2.0.6 on 2018-06-21 10:01

from django.db import migrations, models
import topobank.manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='datafile',
            field=models.FileField(default=0, upload_to=topobank.manager.models.user_directory_path),
            preserve_default=False,
        ),
    ]
