# Generated by Django 2.1.7 on 2019-04-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_surface_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surface',
            options={'permissions': (('share_surface', 'Share surface'),)},
        ),
        migrations.AlterField(
            model_name='surface',
            name='category',
            field=models.TextField(choices=[('exp', 'Experimental data'), ('sim', 'Simulated data'), ('dum', 'Dummy data')], null=True),
        ),
    ]
