# Generated by Django 2.0.6 on 2018-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_surface_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
