# Generated by Django 2.1.7 on 2019-05-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190426_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surface',
            options={'permissions': (('share_surface', 'Can share surface'),)},
        ),
    ]
