# Generated by Django 2.0.6 on 2018-11-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_surface_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topography',
            old_name='surface_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='topography',
            name='dzi_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
