# Generated by Django 2.1.7 on 2019-05-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190507_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surface',
            options={'ordering': ['name'], 'permissions': (('share_surface', 'Can share surface'),)},
        ),
    ]
