# Generated by Django 2.0.6 on 2018-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20181114_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='resolution_x',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topography',
            name='resolution_y',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
