# Generated by Django 2.0.6 on 2018-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20181114_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topography',
            name='dzi_file',
        ),
        migrations.AlterField(
            model_name='topography',
            name='resolution_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='resolution_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='size_y',
            field=models.IntegerField(null=True),
        ),
    ]
