# Generated by Django 2.0.6 on 2018-07-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_topography_surface_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='data_source',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
