# Generated by Django 2.0.6 on 2018-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_topography_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='detrend_mode',
            field=models.TextField(choices=[('center', 'No detrending'), ('height', 'Remove tilt'), ('curvature', 'Remove curvature')], default='center'),
        ),
        migrations.AddField(
            model_name='topography',
            name='height_scale',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='topography',
            name='height_unit',
            field=models.TextField(choices=[('km', 'kilometers'), ('m', 'meters'), ('mm', 'millimeters'), ('µm', 'micrometers'), ('nm', 'nanometers'), ('Å', 'angstrom')], null=True),
        ),
        migrations.AddField(
            model_name='topography',
            name='size_unit',
            field=models.TextField(choices=[('km', 'kilometers'), ('m', 'meters'), ('mm', 'millimeters'), ('µm', 'micrometers'), ('nm', 'nanometers'), ('Å', 'angstrom')], null=True),
        ),
        migrations.AddField(
            model_name='topography',
            name='size_x',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topography',
            name='size_y',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
