# Generated by Django 2.1.7 on 2019-05-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190508_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surface',
            old_name='user',
            new_name='creator',
        ),
    ]
