# Generated by Django 2.0.6 on 2018-08-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20180822_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='height_unit',
            field=models.TextField(choices=[('km', 'kilometers'), ('m', 'meters'), ('mm', 'millimeters'), ('µm', 'micrometers'), ('nm', 'nanometers'), ('Å', 'angstrom')], default='nm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topography',
            name='size_unit',
            field=models.TextField(choices=[('km', 'kilometers'), ('m', 'meters'), ('mm', 'millimeters'), ('µm', 'micrometers'), ('nm', 'nanometers'), ('Å', 'angstrom')], default='nm'),
            preserve_default=False,
        ),
    ]
