# Generated by Django 2.1.7 on 2019-05-27 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_empty_topography_creators(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    topographies = apps.get_model('manager', 'Topography')
    for topo in topographies.objects.all():
        #
        # If the "creator" field for topography is not set,
        # make sure to set it to the "creator" of the surface
        #
        if topo.creator is None:
            topo.creator = topo.surface.creator
            topo.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0007_auto_20190527_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_empty_topography_creators),
    ]
