# Generated by Django 2.0.6 on 2019-01-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190108_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='size_available_in_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topography',
            name='resolution_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='resolution_y',
            field=models.IntegerField(null=True),
        ),
    ]
