# Generated by Django 2.1.7 on 2019-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_topography_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='detrend_mode',
            field=models.TextField(choices=[('center', 'No detrending, but subtract mean height'), ('height', 'Remove tilt'), ('curvature', 'Remove curvature')], default='center'),
        ),
    ]
