# Generated by Django 2.0.6 on 2019-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190110_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='height_scale_available_in_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topography',
            name='size_unit_available_in_file',
            field=models.BooleanField(default=False),
        ),
    ]
