# Generated by Django 2.0.6 on 2019-02-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190111_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topography',
            old_name='height_scale_available_in_file',
            new_name='height_scale_editable',
        ),
        migrations.RenameField(
            model_name='topography',
            old_name='size_available_in_file',
            new_name='size_editable',
        ),
        migrations.RenameField(
            model_name='topography',
            old_name='size_unit_available_in_file',
            new_name='size_unit_editable',
        ),
    ]
