# Generated by Django 2.0.6 on 2019-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190204_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='size_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='topography',
            name='size_y',
            field=models.FloatField(null=True),
        ),
    ]
