# Generated by Django 2.0.6 on 2019-02-07 10:07

from django.db import migrations, models
import topobank.manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190205_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='datafile',
            field=models.FileField(max_length=250, upload_to=topobank.manager.models.user_directory_path),
        ),
    ]
