# Generated by Django 2.1.11 on 2019-11-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20191010_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
    ]
