# Generated by Django 2.1.7 on 2019-03-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20190207_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topography',
            old_name='size_unit',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='topography',
            old_name='size_unit_editable',
            new_name='unit_editable',
        ),
        migrations.RemoveField(
            model_name='topography',
            name='height_unit',
        ),
    ]
