# Generated by Django 2.2.9 on 2020-01-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_topography_is_periodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='datafile_format',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
