# Generated by Django 2.2.13 on 2020-07-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20200626_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
