# Generated by Django 2.2.13 on 2020-07-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20200710_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surface',
            name='is_published',
        ),
        migrations.AddField(
            model_name='surface',
            name='license',
            field=models.CharField(choices=[('cc0-1.0', 'CC0 (Public Domain Dedication)'), ('ccby-4.0', 'CC BY 4.0'), ('ccbysa-4.0', 'CC BY-SA 4.0')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='surface',
            name='publication_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
