# Generated by Django 2.2.13 on 2020-07-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20200720_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surface',
            name='parent',
        ),
    ]
