# Generated by Django 2.2.13 on 2020-10-16 10:14

from django.db import migrations, models


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "topographies/user_{0}/{1}".format(instance.surface.creator.id, filename)


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0019_remove_surface_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="topography",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=user_directory_path),
        ),
    ]
