# Generated by Django 2.2.13 on 2020-10-16 10:14

from django.db import migrations, models
import topobank.manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_remove_surface_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=topobank.manager.models.user_directory_path),
        ),
    ]
