# Generated by Django 2.2.24 on 2021-08-02 12:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20210614_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='instrument_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='topography',
            name='instrument_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='topography',
            name='instrument_type',
            field=models.TextField(choices=[('undefined', 'Instrument of unknown type - all data considered as reliable'), ('microscope-based', 'Microscope-based instrument with known resolution'), ('contact-based', 'Contact-based instrument with known tip radius')], default='undefined'),
        ),
    ]
