# Generated by Django 2.2.24 on 2021-07-15 09:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0022_auto_20210614_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('type', models.TextField(choices=[('undefined', 'Undefined - all data assumed to be reliable'), ('microscope-based', 'Microscope-based with known instrument resolution'), ('contact-based', 'Contact-based with known tip radius')])),
                ('description', models.TextField(blank=True)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topography',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Instrument'),
        ),
    ]
