# Generated by Django 2.2.24 on 2021-08-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20210802_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topography',
            options={'ordering': ['measurement_date', 'pk']},
        ),
    ]
