# Generated by Django 2.2.24 on 2021-07-23 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20210715_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name'], 'permissions': (('share_instrument', 'Can share instrument'),)},
        ),
        migrations.AddField(
            model_name='topography',
            name='instrument_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.TextField(choices=[('undefined', 'Instrument of unknown type - all data considered as reliable'), ('microscope-based', 'Microscope-based instrument with known resolution'), ('contact-based', 'Contact-based instrument with known tip radius')]),
        ),
        migrations.AlterField(
            model_name='topography',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Instrument'),
        ),
    ]
