# Generated by Django 3.2.7 on 2021-09-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20210804_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='instrument_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
