# Generated by Django 3.2.7 on 2021-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_alter_topography_instrument_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='fill_undefined_data_mode',
            field=models.TextField(choices=[('do-not-fill', 'Do not fill undefined data points'), ('harmonic', 'Interpolate undefined data points with harmonic functions')], default='do-not-fill'),
        ),
    ]
