# Generated by Django 3.2.7 on 2021-11-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20211122_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='detrend_mode',
            field=models.TextField(choices=[('center', 'No detrending, but subtract mean height'), ('height', 'Remove tilt'), ('curvature', 'Remove curvature and tilt')], default='center'),
        ),
    ]
