# Generated by Django 3.2.7 on 2021-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_fix_misspelling_in_detrend_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='bandwidth_lower',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='topography',
            name='bandwidth_upper',
            field=models.FloatField(default=None, null=True),
        ),
    ]
