# Generated by Django 3.2.13 on 2022-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20220413_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='short_reliability_cutoff',
            field=models.FloatField(default=None, null=True),
        ),
    ]
