# Generated by Django 3.2.16 on 2022-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_alter_topography_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('surfaces', models.ManyToManyField(to='manager.Surface')),
            ],
        ),
    ]
