# Generated by Django 3.2.16 on 2022-12-20 10:02

from django.db import migrations, models

import topobank.manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_alter_topography_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('surfaces', models.ManyToManyField(to='manager.Surface')),
            ],
            bases=(models.Model, topobank.manager.models.SubjectMixin),
        ),
    ]
