# Generated by Django 3.2.18 on 2023-11-07 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_surfacecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surface',
            name='modification_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
