# Generated by Django 3.2.18 on 2023-09-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_auto_20230915_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='task_error',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='topography',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='task_state',
            field=models.CharField(choices=[('pe', 'pending'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success'), ('no', 'not run')], default='no', max_length=7),
        ),
    ]
