# Generated by Django 3.2.18 on 2023-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_auto_20230923_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surface',
            name='category',
            field=models.CharField(choices=[('exp', 'Experimental data'), ('sim', 'Simulated data'), ('dum', 'Dummy data')], max_length=3, null=True),
        ),
    ]
