# Generated by Django 3.2.18 on 2023-10-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_alter_surface_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='bandwidth_lower',
            field=models.FloatField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='bandwidth_upper',
            field=models.FloatField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='height_scale_editable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='topography',
            name='resolution_x',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='resolution_y',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='short_reliability_cutoff',
            field=models.FloatField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='size_editable',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='topography',
            name='unit_editable',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
