# Generated by Django 3.2.18 on 2023-10-24 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_auto_20231021_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topography',
            name='resolution_x',
            field=models.IntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='topography',
            name='resolution_y',
            field=models.IntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='topography',
            name='size_x',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='topography',
            name='size_y',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
