# Generated by Django 3.2.18 on 2023-11-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_auto_20231108_1315'),
        ('manager', '0041_auto_20231024_2107'),
    ]

    operations = [
    ]
