# Generated by Django 3.2.18 on 2023-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_merge_0035_auto_20231108_1315_0041_auto_20231024_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='is_periodic_editable',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
