# Generated by Django 3.2.18 on 2023-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_alter_topography_instrument_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='data_history',
            field=models.CharField(choices=[('raw', 'Raw Data'), ('app', 'Automatically post-processed by my instrument'), ('mpp', 'Manually post-processed')], max_length=3, null=True),
        ),
    ]
