# Generated by Django 4.2.7 on 2024-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_surfacegroupobjectpermission_surfaceuserobjectpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='task_memory',
            field=models.IntegerField(null=True),
        ),
    ]
