# Generated by Django 4.2.7 on 2024-01-24 19:01

import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_alter_surface_creation_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Property_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tagulous_Property_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_categorical', models.CharField(blank=True, null=True)),
                ('value_numerical', models.FloatField(blank=True, null=True)),
                ('name', tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.tagulous_property_name')),
                ('unit', tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.tagulous_property_unit')),
            ],
        ),
        migrations.AddField(
            model_name='surface',
            name='properties',
            field=models.ManyToManyField(to='manager.property'),
        ),
    ]
