# Generated by Django 4.2.7 on 2024-03-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_rename_tagmodel_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurfaceCollection',
        ),
    ]
