# Generated by Django 4.2.7 on 2024-03-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_tagulous_property_unit_tagulous_property_name_and_more'),
        ('manager', '0050_delete_surfacecollection'),
    ]

    operations = [
    ]
