# Generated by Django 4.2.7 on 2024-03-20 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_merge_20240310_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.surface')),
                ('tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.tag')),
                ('topography', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.topography')),
            ],
        ),
        migrations.CreateModel(
            name='FileManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('kind', models.IntegerField(choices=[(0, 'Attachment')])),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Present'), (2, 'Missing')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fileparent')),
            ],
        ),
    ]
