# Generated by Django 4.2.7 on 2024-03-19 10:01

from django.db import migrations, models
from django.db.migrations.operations import RunPython


def migrate_tagulous_fields_forwards(apps, schema_editor):
    PropertyModel = apps.get_model("manager", "Property")
    PropertyNameModel = apps.get_model("manager", "Tagulous_Property_name")
    PropertyUnitModel = apps.get_model("manager", "Tagulous_Property_unit")

    for property in PropertyModel.objects.all():
        nameTag = PropertyNameModel.objects.get(id=int(property.name))
        property.name = nameTag.name
        if property.unit != None:
            unitTag = PropertyUnitModel.objects.get(id=int(property.unit))
            property.unit = unitTag.name
        property.save()


def migrate_tagulous_fields_backwards(apps, schema_editor):
    PropertyModel = apps.get_model("manager", "Property")
    PropertyNameModel = apps.get_model("manager", "Tagulous_Property_name")
    PropertyUnitModel = apps.get_model("manager", "Tagulous_Property_unit")

    for property in PropertyModel.objects.all():
        nameTag = PropertyNameModel.objects.create(name=property.name)
        property.name = nameTag.id
        if property.unit != None:
            unitTag = PropertyUnitModel.objects.create(name=property.unit)
            property.unit = unitTag.id
        property.save()

class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_merge_20240310_1149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagulous_property_unit',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.TextField(default='prop'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_tagulous_fields_forwards, migrate_tagulous_fields_backwards),
        migrations.DeleteModel(
            name='Tagulous_Property_name',
        ),
        migrations.DeleteModel(
            name='Tagulous_Property_unit',
        ),
    ]
