# Generated by Django 4.2.11 on 2024-04-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_alter_tagulous_property_unit_unique_together_and_more'),
        ('manager', '0052_fileparent_filemanifest'),
    ]

    operations = [
    ]
