# Generated by Django 4.2.14 on 2024-08-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_alter_tagulous_property_unit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('surface', 'name')},
        ),
    ]
