# Generated by Django 4.2.11 on 2024-06-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0054_fileparent_filemanifest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileparent',
            name='tag',
        ),
    ]
