# Generated by Django 4.2.15 on 2024-08-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0054_alter_topography_options_property_permissions_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="surfaceuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="surfaceuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="surfaceuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="surfaceuserobjectpermission",
            name="user",
        ),
        migrations.DeleteModel(
            name="SurfaceGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="SurfaceUserObjectPermission",
        ),
    ]
