# Generated by Django 4.2.15 on 2024-08-19 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
        ("manager", "0055_remove_fileparent_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topography",
            options={
                "ordering": ["measurement_date", "pk"],
                "verbose_name": "measurement",
                "verbose_name_plural": "measurements",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="permissions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authorization.permissionset",
            ),
        ),
        migrations.AddField(
            model_name="surface",
            name="permissions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authorization.permissionset",
            ),
        ),
        migrations.AddField(
            model_name="topography",
            name="permissions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authorization.permissionset",
            ),
        ),
    ]
