# Generated by Django 4.2.15 on 2024-08-28 11:37
import math
import os

from django.db import migrations


def generate_manifest(
    name: str,
    nb_grid_pts: tuple[int, int],
    root_directory: str = ".",
    tile_size: int = 256,
    format: str = "jpg",
    meta_format: str = "xml",
):
    """
    Generate the file manifest, i.e. the list of files, that would be generated when
    writing the DZI.

    Parameters
    ----------
    name : str
        Name of the exported file. This is used as a prefix. Output filter
        create the file `name`.xml that contains the metadata and a directory
        `name`_files that contains the rendered image files at different levels.
    nb_grid_pts : tuple of ints
        Number of grid points.
    root_directory : str, optional
        Root directory where to place `name`.xml and `name`_files.
        (Default: '.')
    tile_size : int, optional
        Size of individual tiles. (Default: 256)
    format : str, optional
        Data output format. Note that PNG files have seams at the boundary between
        tiles. Use 'npy' to output raw data in the native numpy format.
        Use 'nc' to output raw data as NetCDF files. (Default: 'jpg')
    meta_format : str, optional
        Format for metadata information (the DZI file), can be 'xml' or
        'json'. (Default: 'xml')

    Returns
    -------
    manifest : list of str
        List with names of files created during write operation
    """

    # Image size
    width, height = nb_grid_pts

    # Write configuration file
    if meta_format == "xml":
        fn = os.path.join(root_directory, name + ".xml")
    elif meta_format == "json":
        fn = os.path.join(root_directory, name + ".json")
    else:
        raise ValueError(f"Unknown metadata format {meta_format}.")
    manifest = [fn]

    # Determine number of levels
    max_level = math.ceil(math.log2(max(width, height)))

    # Loop over levels and write tiles
    root_directory = os.path.join(root_directory, name + "_files")
    for level in range(max_level, -1, -1):
        level_root_directory = os.path.join(root_directory, str(level))

        columns = math.ceil(width / tile_size)
        rows = math.ceil(height / tile_size)

        # Loop over all tiles
        for column in range(columns):
            for row in range(rows):
                # File name for this tile
                fn = os.path.join(level_root_directory, f"{column}_{row}.{format}")

                manifest += [fn]

        width = math.ceil(width / 2)
        height = math.ceil(height / 2)

    return manifest


def forward_func(apps, schema_editor):
    Topography = apps.get_model("manager", "Topography")
    Manifest = apps.get_model("files", "Manifest")
    for topography in Topography.objects.all():
        topography.datafile_manifest = Manifest.create(
            filename=os.path.split(topography.file.name)[1],
            kind="raw",
            uploaded_by=topography.creator,
            file=topography.datafile.file,
        )
        topography.squeezed_datafile_manifest = Manifest.create(
            filename=os.path.split(topography.squeezed_file.name)[1],
            kind="der",
            uploaded_by=topography.creator,
            file=topography.squeezed_datafile.file,
        )
        topography.thumbnail_manifest = Manifest.create(
            filename=os.path.split(topography.thumbnail.name)[1],
            kind="der",
            uploaded_by=topography.creator,
            file=topography.thumbnail.file,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_alter_manifest_uploaded_by"),
        ("manager", "0056_topography_datafile_manifest_topography_deepzoom_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_func),
        migrations.RemoveField(
            model_name="topography",
            name="datafile",
        ),
        migrations.RemoveField(
            model_name="topography",
            name="squeezed_datafile",
        ),
        migrations.RemoveField(
            model_name="topography",
            name="thumbnail",
        ),
    ]
