# Generated by Django 4.2.15 on 2024-08-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0057_migrate_file_field_to_manifest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topography",
            name="datafile",
        ),
        migrations.RemoveField(
            model_name="topography",
            name="squeezed_datafile",
        ),
        migrations.RemoveField(
            model_name="topography",
            name="thumbnail",
        ),
    ]
