# Generated by Django 4.2.15 on 2024-08-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0057_remove_topography_datafile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topography",
            old_name="datafile_manifest",
            new_name="datafile",
        ),
        migrations.RenameField(
            model_name="topography",
            old_name="squeezed_datafile_manifest",
            new_name="squeezed_datafile",
        ),
        migrations.RenameField(
            model_name="topography",
            old_name="thumbnail_manifest",
            new_name="thumbnail",
        ),
    ]
