# Generated by Django 4.2.15 on 2024-08-31 06:00

import django.db.models.deletion
from django.db import migrations, models


def forward_func(apps, schema_editor):
    Topography = apps.get_model("manager", "Topography")
    Surface = apps.get_model("manager", "Surface")
    Folder = apps.get_model("files", "Folder")
    for t in Topography.objects.filter(attachments__isnull=True):
        t.attachments = Folder.objects.create(permissions=t.permissions, read_only=True)
        t.save()
    for s in Surface.objects.filter(attachments__isnull=True):
        s.attachments = Folder.objects.create(permissions=s.permissions, read_only=True)
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0059_rename_datafile_manifest_topography_datafile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surface",
            name="attachments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="files.folder",
            ),
        ),
        migrations.AddField(
            model_name="topography",
            name="attachments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="files.folder",
            ),
        ),
        migrations.RunPython(forward_func),
    ]
