# Generated by Django 4.2.16 on 2024-09-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0061_topography_launcher_task_id_alter_topography_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='task_traceback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topography',
            name='task_state',
            field=models.CharField(choices=[('pe', 'pending'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success'), ('no', 'not run')], default='no', max_length=2),
        ),
    ]
