# Generated by Django 4.2.16 on 2024-09-23 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0064_alter_surface_tags_alter_topography_tags"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Property",
                ),
            ],
            # Don't drop the table
            database_operations=[],
        ),
    ]
