# Generated by Django 4.2.20 on 2025-04-27 09:42

from django.db import migrations, models
import django.db.models.deletion
import topobank.authorization.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('files', '0007_alter_manifest_unique_together'),
        ('manager', '0065_delete_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(null=True, unique=True)),
                ('launcher_task_id', models.UUIDField(null=True, unique=True)),
                ('task_state', models.CharField(choices=[('pe', 'pending'), ('st', 'started'), ('re', 'retry'), ('fa', 'failure'), ('su', 'success'), ('no', 'not run')], default='no', max_length=2)),
                ('task_memory', models.BigIntegerField(null=True)),
                ('task_error', models.TextField(default='')),
                ('task_traceback', models.TextField(null=True)),
                ('creation_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_containers', to='files.manifest')),
                ('permissions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.permissionset')),
            ],
            options={
                'abstract': False,
            },
            bases=(topobank.authorization.mixins.PermissionMixin, models.Model),
        ),
    ]
