# Generated by Django 5.2.5 on 2025-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0068_surface_owner_alter_surface_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surface",
            old_name="creation_datetime",
            new_name="creation_time",
        ),
        migrations.RenameField(
            model_name="surface",
            old_name="modification_datetime",
            new_name="modification_time",
        ),
        migrations.RenameField(
            model_name="topography",
            old_name="modification_datetime",
            new_name="modification_time",
        ),
        migrations.RemoveField(
            model_name="topography",
            name="creation_datetime",
        ),
        migrations.AddField(
            model_name="surface",
            name="deletion_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="topography",
            name="deletion_time",
            field=models.DateTimeField(null=True),
        ),
    ]
