# Generated by Django 5.2.4 on 2025-08-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0069_rename_creation_datetime_surface_creation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcontainer',
            old_name='update_time',
            new_name='modification_time',
        ),
    ]
