# Generated by Django 5.2.5 on 2025-10-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0070_rename_update_time_zipcontainer_modification_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surface',
            options={'ordering': ['name']},
        ),
    ]
