# Generated by Django 5.2.7 on 2025-11-10 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0071_alter_surface_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='surface',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='surface',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='surface',
            old_name='owner',
            new_name='owned_by',
        ),
        migrations.RenameField(
            model_name='surface',
            old_name='modification_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='topography',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='topography',
            old_name='modification_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='zipcontainer',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='zipcontainer',
            old_name='modification_time',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topography',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='surface',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topography',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topography',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
