# Generated by Django 5.2.10 on 2026-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0075_add_tag_path_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='topography',
            name='task_timer',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='zipcontainer',
            name='task_timer',
            field=models.JSONField(null=True),
        ),
    ]
