# Generated by Django 5.2.10 on 2026-02-02 16:37
# Modified to be state-only: Indexes already exist from migrations 0073 and 0074 (created via RunSQL)

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_add_permission_performance_indexes'),
        ('files', '0009_rename_upload_confirmed_manifest_confirmed_at'),
        ('manager', '0077_alter_task_state'),
        ('organizations', '0005_fix_plugins_available_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # State-only migration: Indexes already exist in database from RunSQL in migrations 0073 and 0074
        # These operations only update Django's migration state to know about the indexes
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='surface',
                    index=models.Index(condition=models.Q(('deletion_time__isnull', True)), fields=['name'], name='surface_active_name_idx'),
                ),
                migrations.AddIndex(
                    model_name='topography',
                    index=models.Index(condition=models.Q(('deletion_time__isnull', True)), fields=['name'], name='topography_active_name_idx'),
                ),
            ],
            database_operations=[
                # No database operations - indexes already exist
            ],
        ),
    ]
