# Generated by Django 5.2.15 on 2026-06-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0079_backfill_owned_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surface",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
