# Generated by Django 5.2.16 on 2026-07-24 21:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.models import Value


def _flatten(s):
    if s is None:
        return ""
    return s.replace(".", " ").replace("/", " ")


def backfill_search_vectors(apps, schema_editor):
    """Populate the search vector for all existing datasets.

    Mirrors ``Surface.build_search_document`` using historical models. From
    here on, signal handlers keep the vector up to date; a full rebuild is
    available via the ``rebuild_search_vectors`` management command.
    """
    Surface = apps.get_model("manager", "Surface")
    for surface in Surface.objects.all().iterator():
        parts = [
            _flatten(surface.name),
            surface.description or "",
            surface.created_by.name if surface.created_by is not None else "",
        ]
        parts += [_flatten(tag.name) for tag in surface.tags.all()]
        for topography in surface.topography_set.all():
            parts += [
                _flatten(topography.name),
                topography.description or "",
                (
                    topography.created_by.name
                    if topography.created_by is not None
                    else ""
                ),
            ]
            parts += [_flatten(tag.name) for tag in topography.tags.all()]
        document = " ".join(part for part in parts if part)
        Surface.objects.filter(pk=surface.pk).update(
            search_vector=SearchVector(Value(document), config="english")
        )


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0080_alter_surface_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="surface",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="surface",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="surface_search_idx"
            ),
        ),
        migrations.RunPython(
            backfill_search_vectors, reverse_code=migrations.RunPython.noop
        ),
    ]
