# Generated by Django 5.2.16 on 2026-08-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0081_surface_search_vector_surface_surface_search_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="topography",
            name="detrend_parameters",
            field=models.JSONField(default=None, editable=False, null=True),
        ),
    ]
