# Generated by Django 5.2.16 on 2026-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0082_topography_detrend_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="topography",
            name="undefined_data_fraction",
            field=models.FloatField(default=None, editable=False, null=True),
        ),
    ]
