# Generated by Django 5.2.15 on 2026-08-12 19:53
# Modified: the index rebuilds are state-only.

from django.db import migrations, models


class Migration(migrations.Migration):
    """Rename ``deletion_time`` to ``deleted_at`` on Surface and Topography.

    Every other timestamp on these models is ``<verb>_at`` — ``created_at``,
    ``updated_at`` — so ``deletion_time`` was the lone outlier.
    """

    dependencies = [
        ("manager", "0084_deleted_by"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="surface",
                    name="surface_list_idx",
                ),
                migrations.RemoveIndex(
                    model_name="surface",
                    name="surface_active_name_idx",
                ),
                migrations.RemoveIndex(
                    model_name="topography",
                    name="topography_list_idx",
                ),
                migrations.RemoveIndex(
                    model_name="topography",
                    name="topography_active_name_idx",
                ),
            ],
            database_operations=[],
        ),
        migrations.RenameField(
            model_name="surface",
            old_name="deletion_time",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="topography",
            old_name="deletion_time",
            new_name="deleted_at",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="surface",
                    index=models.Index(
                        fields=["deleted_at", "name"], name="surface_list_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="surface",
                    index=models.Index(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=["name"],
                        name="surface_active_name_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="topography",
                    index=models.Index(
                        fields=["deleted_at", "name"], name="topography_list_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="topography",
                    index=models.Index(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=["name"],
                        name="topography_active_name_idx",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
