# Generated by Django 3.2.15 on 2022-09-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Organization')),
                ('plugins_available', models.CharField(blank=True, help_text='Comma-separated list of names of plugin packages\n                                         available for this organization.\n                                         ', max_length=255, verbose_name='Available Plugins')),
                ('group', models.OneToOneField(help_text='Group which corresponds to members of this organization.', on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
