# Generated by Django 5.2.5 on 2025-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Name of Organization"
            ),
        ),
    ]
