# Generated by Django 5.2.13 on 2026-04-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0005_alter_userpermission_related_name"),
        ("organizations", "0006_organization_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="allow",
            field=models.CharField(
                choices=[
                    ("view", "Read-only access"),
                    ("edit", "Change the model data"),
                    ("full", "Grant/revoke permissions of other users"),
                ],
                default="view",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrganizationPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow",
                    models.CharField(
                        choices=[
                            ("view", "Read-only access"),
                            ("edit", "Change the model data"),
                            ("full", "Grant/revoke permissions of other users"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_permissions",
                        to="authorization.permissionset",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "organization")},
            },
        ),
    ]
