#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

#
# See commands here:
#   https://cookiecutter-django.readthedocs.io/en/latest/deployment-with-docker.html#building-running-production-stack
#
# The migration should not be run automatically in production
#python manage.py migrate
#python manage.py register_analysis_functions

#envsubst < orcid.yaml.template > orcid.yaml
#python manage.py loaddata -v 2 orcid.yaml

python /app/manage.py collectstatic --noinput

# This location for gunicorn is used with miniconda as image
GUNICORN=/opt/conda/bin/gunicorn

# This location would be used with python3.7-alpine as base image
# GUNICORN=/usr/local/bin/gunicorn

${GUNICORN} config.wsgi --bind 0.0.0.0:5000 --chdir=/app --worker-class gevent --timeout 300 --log-level debug --limit-request-line 8190

# Default maximum for request line is 4094.
# See here: https://docs.gunicorn.org/en/latest/settings.html?highlight=limit_request_line#limit-request-line
# The value 0 would remove the limit but may be used for DDOS attacks.

