from topobank.analysis.functions import SecondTestImplementation, TestImplementation
from topobank.analysis.registry import register_implementation

register_implementation(TestImplementation)
register_implementation(SecondTestImplementation)
