# Generated by Django 5.2.16 on 2026-07-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    (
                        "can_skip_terms",
                        "Can skip all checkings for terms and conditions.",
                    ),
                )
            },
        ),
    ]
