
---

# Following only works if sudo does not require password
#- name: Prepare test server host
#  hosts: topobank-test-vm
#  remote_user: roettger
#  become: yes
#  tasks:
#  - name: Update packages
#    apt:
#      update_cache: yes
#      upgrade: yes
#
#  - name: Install packages
#    apt:
#      pkg:
#      - python3-pip
#      - docker.io
#      - docker-compose
#
#  - name: Start docker
#    service:
#      name: docker
#      state: started
#
#  - name: Create 'topobank' user
#    ansible.builtin.user:
#      name: topobank
#      comment: User running the analyses
#      shell: /bin/bash
#      groups: docker
#
#  - name: Add public key
#    ansible.posix.authorized_key:
#      user: topobank
#      state: present
#      key: "{{ lookup('file', '/home/michael/.ssh/id_rsa.pub') }}"
#
##############
## plus (not coded yet)
##############
# Add a line to /etc/hosts
# 127.0.1.1 conengrk conengrk.vm.privat
#
############

 - name: Prepare containers
   hosts: topobank-test-vm
   remote_user: topobank
   tasks:
     - name: GitHub checkout
       ansible.builtin.git:
         repo: https://github.com/ContactEngineering/TopoBank.git
         dest: /home/topobank/topobank
         version: 21_shift_analyses_to_cloud
         # version: 0.16.2
     - name: Copy environment files
       copy:
         src: ../.envs
         dest: /home/topobank/topobank/
         owner: topobank
         mode: u=rw,g=,o=
     - name: Copy django config file for testserver
       copy:
         remote_src: True
         src: /home/topobank/topobank/.envs/.production/.django.testserver
         dest: /home/topobank/topobank/.envs/.production/.django
         owner: topobank
         mode: u=rw,g=,o=
     - name: Build docker containers with docker compose
       community.docker.docker_compose:
         project_src: /home/topobank/topobank
         #files: local.yml
         files: production.yml
         state: present
         build: yes
#         remove_orphans: yes
#         state: present
#         project_name: topobank-celery
#         services: celeryworker
#         definition:
#           version: '3'
#           services:
#             celeryworker:
#               image: topobank_celeryworker
#               ports: []
#               command: /start-celeryworker
#               build:
#                 context: .
#                 dockerfile: ./compose/production/django/Dockerfile
#               env_file:
#                 - ./.envs/.local/.django
#                 - ./.envs/.local/.postgres


