# Generated by Django 3.2.18 on 2023-10-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0021_auto_20230916_0908"),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'analysis_dependency',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.SmallIntegerField()),
                ('minor', models.SmallIntegerField()),
                ('micro', models.SmallIntegerField(null=True)),
                ('extra', models.CharField(max_length=100, null=True)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.dependency')),
            ],
            options={
                'db_table': 'analysis_version',
                'unique_together': {('dependency', 'major', 'minor', 'micro', 'extra')},
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_since', models.DateTimeField(auto_now_add=True)),
                ('versions', models.ManyToManyField(to='taskapp.Version')),
            ],
            options={
                'db_table': 'analysis_configuration',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]

