# Generated by Django 2.0.6 on 2018-08-31 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180822_1620'),
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='topography',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.Topography'),
            preserve_default=False,
        ),
    ]
