# Generated by Django 4.2.15 on 2024-09-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="configuration",
            table=None,
        ),
        migrations.AlterModelTable(
            name="dependency",
            table=None,
        ),
        migrations.AlterModelTable(
            name="version",
            table=None,
        ),
    ]
