# Generated by Django 2.0.6 on 2018-09-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_analysis_topography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='topography',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
