FROM caddy:2-alpine

COPY ./compose/production/caddy/Caddyfile /etc/caddy/Caddyfile
COPY ./compose/production/caddy/certificate.crt /etc/caddy/certificate.crt
COPY ./compose/production/caddy/private.key /etc/caddy/private.key
