# Generated by Django 4.2.15 on 2024-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_folder_permissions_manifest_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manifest",
            old_name="file_name",
            new_name="filename",
        ),
        migrations.RemoveField(
            model_name="manifest",
            name="file_type",
        ),
        migrations.AlterField(
            model_name="manifest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("N/A", "Kind is unknown"),
                    ("att", "Attachment"),
                    ("der", "Data derived from a raw data file"),
                    ("raw", "Raw data file as uploaded by a user"),
                ],
                default="N/A",
                max_length=3,
            ),
        ),
    ]
