# Generated by Django 4.2.15 on 2024-08-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_alter_manifest_uploaded_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manifest",
            old_name="upload_finished",
            new_name="upload_confirmed",
        ),
    ]
