# Generated by Django 4.2.15 on 2024-08-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_rename_upload_finished_manifest_upload_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="read_only",
            field=models.BooleanField(default=True, verbose_name="read_only"),
        ),
    ]
