# Generated by Django 4.2.15 on 2024-09-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_folder_read_only"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="manifest",
            unique_together={("folder", "filename")},
        ),
    ]
