# Generated by Django 5.2.7 on 2025-11-10 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_manifest_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='uploaded_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='manifest',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
