# Generated by Django 5.2.7 on 2025-11-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_rename_created_manifest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='upload_confirmed',
            new_name='confirmed_at',
        ),
    ]
