# Generated by Django 5.2.15 on 2026-08-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0010_rename_folder_to_manifestset"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifest",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=127),
        ),
        migrations.AddField(
            model_name="manifest",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="manifest",
            name="size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manifest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("N/A", "Kind is unknown"),
                    ("att", "File attachment uploaded by a user"),
                    ("der", "Data derived from a raw data file"),
                    ("raw", "Raw data file as uploaded by a user"),
                ],
                default="N/A",
                max_length=3,
            ),
        ),
    ]
