# Generated by Django 5.2.15 on 2026-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0011_manifest_note_size_bytes_content_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="manifest",
            index=models.Index(
                condition=models.Q(("confirmed_at__isnull", True), ("kind", "att")),
                fields=["created_at"],
                name="manifest_unconfirmed_att_idx",
            ),
        ),
    ]
