# Generated by Django 5.2.11 on 2026-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_manifestset_storage_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestset',
            name='storage_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
    ]
