name: Test code functionality

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: topobank-test
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgres://postgres:secret@localhost/topobank-test

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up python3 ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install .[dev]
        python manage.py collectstatic

    - name: Test
      run: pytest -v
